### ISSUE TITLE
Macro: Set Fatigue

### ISSUE THREAD

**Issue by toastygm** [toastygm/HarnMaster-3-FoundryVTT#104]
A macro that will expose the ability to set fatigue, either to a particular absolute value or relative (+ or -)

**Comment by toastygm** [comment]
If the new value starts with a + or -, it is a change by that amount.  If it is just a number (no sign), the new value will be set at that value.  Obviously, negative quantities are not allowed and will become zero instead.

**Comment by scooper4711** [comment]
Fixed in 0.7.18
