### ISSUE TITLE
Standard Compendium Items appear to be corrupt

### ISSUE THREAD

**Issue by jpmcdonald** [toastygm/HarnMaster-3-FoundryVTT#108]
I get this message when I attempt to open the Std Magic and Std Religion compendiums.
![Screen Shot 2020-11-26 at 12 06 36 PM](https://user-images.githubusercontent.com/24255029/100382120-339c6780-2fe0-11eb-97cc-32017e553289.png)

I reinstalled the system and get the same error.

**Comment by toastygm** [comment]
Thanks for bringing this to my attention.  I recently made a change to the data model, and it must have broken those compendiums.  I will fix them and upload today.
