### ISSUE TITLE
spell macro not working?

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#111]
I borrowed some code for spell effects from FX master. The code works exactly as intended when placed in the macro bar.
However, if i put it in the macro input box for a spell, it doesn't.
```
function castSpell(effect) {
    const tokens = canvas.tokens.controlled;
    if (tokens.length == 0) {
        ui.notifications.error("Please select a token");
        return;
    }
    game.user.targets.forEach((i, t) => {
        canvas.fxmaster.drawSpecialToward(effect, tokens[0], t);
    })
}

castSpell({
    file: "modules/fxmaster/specials/jinker/dragonBornBlack-CopperAcid30x5Line.webm",
    anchor: {
        x: -.08,
        y: 0.5
    },
    speed: 0,
    angle: 0,
    scale: {
    x: 1.0,
    y: 1.0
}
});```

**Comment by toastygm** [comment]
Sorry, I wasn't clear.  I put in the field for the macro, but I have not implemented macros yet.

**Comment by toastygm** [comment]
Given the complexities of handling macros, the "Macro" field is likely to simply invoke a listed macro (such as from the macro bar); but I still need to think this through.
