### ISSUE TITLE
Mounted combat option

### ISSUE THREAD

**Issue by Fjaard** [toastygm/HarnMaster-3-FoundryVTT#119]
So far I am loving this implementation of HM3, I have noticed that I am unable to override encumbrance values to add a mounted option, I think it would be useful to have a toggle option for that

**Comment by toastygm** [comment]
I haven't forgotten about this request; but it is a lot more complicated than it might seem.  This affects a lot of different parts of the system.  I think it is a worthwhile enhancement, and I do plan on implementing it, but it may take a little bit.

**Comment by Fjaard** [comment]
While I was hoping to see mounted combat on the 1.0 update, I have been
amazed at the progress you have made so far. I started my campaign only a
few months ago now on roll20, but immediately switched my players over in
large part because of your system. Thank you again, the work you are doing
has the ability to make harnmaster more accessible to new players than ever
before.

**Comment by toastygm** [comment]
I apologize for not mentioning this earlier, but this was implemented in version 1.1.0 using the new "Effects" feature.  It is now possible to specify an "Effect" that will multiply encumbrance by 0.5 to support the mounted combat mechanisms.  If you need further assistance with this, please post a message in the Discord regarding this.

**Comment by Fjaard** [comment]
That's awesome! Thank you so much, I'm learning python now, but maybe next
semester I'll learn java and might be able to help!

**Comment by toastygm** [comment]
Please be sure to join my Discord server where there are updates and you
can ask for help using HM3 on Foundry VTT.

https://discord.gg/f2Qjar3Rqv
