### ISSUE TITLE
Container with limited visibility - icons for edit and delete should be greyed out

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#126]
This is the screenshot for a player with limited visibility rights to a container. Note that the delete and edit icons are not greyed out. Neither works, so this is just cosmetic.
<img width="659" alt="Screen Shot 2020-12-06 at 5 06 47 PM" src="https://user-images.githubusercontent.com/1970249/101297300-88f92580-37e5-11eb-8ae3-a3f8a085abe5.png">

**Comment by toastygm** [comment]
A player with Limited Visibility rights should not see any of the contents of a container.  It is effectively "closed" as far as they are concerned.  They need to unlock it or open it.  That would be implemented by them gaining owner privs.

**Comment by scooper4711** [comment]
Fixed in 0.7.18
