### ISSUE TITLE
Support optional rule: Reaction zone

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#129]
To suppor the optional rule of Reaction Zone (Combat 6), allow for PCs to make an attack when it's not their turn.
One suggestion is if it's not a player's turn and they make an attack, there is a configurable setting a la "it's not your turn" to
* display a warning but allow the attack to proceed
* display a dialog to the GM asking if it's ok to allow the attack.
* Politely tell the player "no".

**Comment by toastygm** [comment]
I think I am going to leave Enhanced Combat the way it is, and not add the complexity involved in this to it.  If the GM/Players want to allow this rule, then they can either play it out by hand or use the "Legacy" attack/damage/injury mechanisms/macros to do it.
