### ISSUE TITLE
Feature request: roll location of dropped item

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#132]
Going through the rules, spotted something which might be fun to add to the fumble roll.
If an actor fails the fumble roll, roll to see where any dropped item lands:
From the rules: (skills 21)
If an item is dropped, roll 1d10: a number 1–6 indicates the item falls in an adjacent hex (1=N, 2=NE, 3=SE, 4=S, 5=SW and 6=NW); a roll of 7–10 indicates the item has fallen in the same hex.

Could make picking up that dropped sword a little more interesting...

**Comment by jpmcdonald** [comment]
This can easily be done as a roll table by the GM with the basic platform.

Stephen Cooper wrote:

**Comment by scooper4711** [comment]
Sure. Or I could roll a d10.

What I thought would be fun/added flavor was to automatically roll that as part of the failed fumble. 
"Hero 1 fails the fumble roll. Item is dropped one hex NW"

This is just a fun add-on and isn't critical functionality in any way.

**Comment by toastygm** [comment]
I think I will leave this up to the GM and players to play out themselves, rather than making an automatic roll.
