### ISSUE TITLE
Feature request: Max carrying

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#133]
in 0.7.13, a person has an infinite carry weight. Looking at Skills 21, I think a max carry weight of END x 10 would be better to indicate.

**Comment by toastygm** [comment]
Thanks, I wasn't aware of that rule.  I will make this change.

**Comment by scooper4711** [comment]
Don't limit, just highlight in red if you exceed. B/c then you can start having the player make endurance tests.

**Comment by scooper4711** [comment]
Fixed in 0.7.18
