### ISSUE TITLE
BUG: beast actor has h scrollbar under injury/shock/stumble/fumble

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#138]
There is an unnecessary scrollbar on beasts under injury/shock/etc.
This screenshot is from 0.7.10, issue persists in 0.7.18

<img width="660" alt="Screen Shot 2020-12-10 at 4 18 19 PM" src="https://user-images.githubusercontent.com/1970249/101842274-ea323900-3b04-11eb-8ff1-fae796dd794f.png">

**Comment by toastygm** [comment]
I know, its been there forever, and I don't know how to get rid of it.

I'll keep trying, but this is not a showstopper.

**Comment by scooper4711** [comment]
Fixed in 0.7.19. Looks much better!
