### ISSUE TITLE
Text reflows when hovering over the filter bars

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#145]
Yes, this is a super minor nit.
When you hover over the name and it highlights the text entry field in red, the rest of the page is stable.
When you hover over the skills filter or gear filter, the text below it jumps a bit.
SUPER MINOR. Just logging a bug so we don't lose track of it.
Feel free to close w/o fixing.

**Comment by toastygm** [comment]
This will not be fixed.
