### ISSUE TITLE
Current weight not summed up on Creature actors

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#146]
Note the capacity is /130. No numerator.

<img width="669" alt="Screen Shot 2020-12-10 at 9 20 35 PM" src="https://user-images.githubusercontent.com/1970249/101861556-8e2fda80-3b2d-11eb-868f-7e643d8b60d9.png">

**Comment by toastygm** [comment]
For the moment, I am going to simply remove the capacity from creatures, until I can get around to managing creature encumbrance correctly.

**Comment by scooper4711** [comment]
Resolved in 0.7.20
