### ISSUE TITLE
Reactive design

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#147]
Something to consider is how to re-flow the UI for small screens.
Feel free to close this w/o addressing if it's not on your roadmap.
<img width="501" alt="Screen Shot 2020-12-10 at 9 22 18 PM" src="https://user-images.githubusercontent.com/1970249/101861695-ecf55400-3b2d-11eb-8c72-f4a38d993761.png">

**Comment by toastygm** [comment]
This will not be implemented
