### ISSUE TITLE
Compendium:  Kurbul Greaves missing location data

### ISSUE THREAD

**Issue by mrg67** [toastygm/HarnMaster-3-FoundryVTT#153]
In the Std Armor folder of the Compendium, the Kurbul Greaves armor has no locations defined.

![image](https://user-images.githubusercontent.com/74210758/101936136-04b3f300-3b95-11eb-8854-8118732eeda1.png)

**Comment by scooper4711** [comment]
confirmed.
I checked plate greaves and they're correct.
