### ISSUE TITLE
enhancement: allow for gear drop on actor with limited visibility

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#155]
To allow for PCs to share items with each other, allow for dropping gear onto a character sheet where the player has limited visibility (FFF view)

**Comment by toastygm** [comment]
You realize there is a viable denial-of-service attack possible here.  If you get attacked, you and your friends each "give" your opponent some heavy object, like a rock.  Now his physical penalty goes up, and his skills all get worse!

**Comment by toastygm** [comment]
That is a bit tongue-in-cheek, but it does illustrate the fact that you are not supposed to be able to interact much with a limited actor, aside from attacking them.

**Comment by toastygm** [comment]
It is kind of Kludgy, but you could always create an Actor container and use that to transfer goods between limited actors...

**Comment by scooper4711** [comment]
Fair. It could be an actor that is never placed out, but where the players could swap gear with each other. 
You can close this.
