### ISSUE TITLE
Missile Combat:  range calculation

### ISSUE THREAD

**Issue by mrg67** [toastygm/HarnMaster-3-FoundryVTT#156]
Is the range calculation (number of 5' hexes) working correctly in the example shown below?  I guess I would typically count this as 4 hexes.

![image](https://user-images.githubusercontent.com/74210758/101947836-f02c2680-3ba5-11eb-85dc-a5ad7c2b148c.png)

**Comment by toastygm** [comment]
I am currently not counting range using hexes, I am performing it using cartesian canvas coordinates (x1,y1 to x2,y2).  Therefore, the calculation may not end up being what it would be if the calculation were being performed by counting hexes.

I plan to improve this in the future, calculating range using hexes, but that is a future enhancement.

**Comment by mrg67** [comment]
That's fair, and I think calculating distance by cartesian canvas coordinates is probably a much simpler and solid method.  I'm still seeing some discrepancies though.  I ran a test:

Scene Grid Size:  100 pixels
Scene Grid Scale:  2 ft.
Actor 1:  x=200, y=0
Actor 2:  x=200, y=1000

Visually, the icons are 10 squares/grids apart.  The Measure Tool confirms a distance (center-center) of 20'

When I have one character attack the other with a missile weapon, it shows the distance as 10 (see screenshot).  I'm assuming that is intended to mean 10 Harn Hexes, or 50 ft...but I don't see how that corresponds to anything else...unless you are doing a raw pixel calculation of 1000 pixel distance divided by 100 pixel grid size.  It seems like you would have to further multipy that by the grid scale of 2 (for 2 ft.) to get the total units (feet), then divide it by 5 to get the Harnic "hexes".

[pixel distance] / [pixel grid] * [scale] / 45

![image](https://user-images.githubusercontent.com/74210758/101966797-02ba5600-3bce-11eb-8a4a-9a367330e576.png)

**Comment by toastygm** [comment]
Ensure you have set the range setting the way you want.  Please go into the
"System Settings" tab and select "Range Units" the way you want: either
"Scene units" (e.g., feet) or "Grid Units" (grids).

I currently do nothing regarding "Harnic Grids".  It is up to you to
setup the system in a Harnic-compatible fashion.  If you setup the scene
using a hexagonal grid, and set the units to 1 hex = 5 feet (the Harnic
standard), then things should start working as you expect, with the caveat
I provided earlier.

I take the x,y coordinate of the attacker, and the x,y coordinate of the
defender, calculate the distance, and divide the result by the grid ratio
(the grid is generally 100 points per grid unit, although that can be
configured).  That gives me "ideal grid units". If you have requested grid
units, I stop there and return that result.  If instead you have asked for
Scene units, then I multiply that number by the scene scale (usually 5 feet
per grid, but also configurable) to achieve the Scene units (so 5 grid
units would become 25 feet).

Hope this helps.

Tom.

--
*Tom Rodriguez*
*w:* www.casualinsight.com | *e:* tmrodrig@gmail.com
*LinkedIn:* www.linkedin.com/in/tomrodriguez
*Twitter:* @TomRodriguezCI <https://twitter.com/TomRodriguezCI>

**Comment by mrg67** [comment]
That is helpful information.  Thank you.  I didn't even know about the System Settings.

In order to make this work, I had to go back and edit the ranges for the missile weapons so that they were in feet, not hexes...as they show in the HM3 tables.  Now it's working as expected.

**Comment by toastygm** [comment]
I have modified the range calculations...so this should be working now.
