### ISSUE TITLE
Combat Result:  should result in Fumble roll?

### ISSUE THREAD

**Issue by mrg67** [toastygm/HarnMaster-3-FoundryVTT#161]
Please see the attached screenshot.
It's the first hit of the combat, resulting in a M1 wound on the upper arm.
Expected result:  Shock Roll and Fumble Roll
Actual result:  Shock Roll

![image](https://user-images.githubusercontent.com/74210758/101999787-5ba0f180-3c95-11eb-9278-677fd7cfe8f9.png)

**Comment by toastygm** [comment]
I don’t have the rules right in front of me right now; are you saying that any injury to the arm causes a fumble roll? Please give me the reference in the HM3 rules.

**Comment by mrg67** [comment]
Unless I'm interpreting the Injury Table wrong, anywhere there is a black diamond symbol, that indicates a Fumble or Stumble roll should occur.

Ahhhh...it might be an optional rule.  The only reference I can find is in the sidebar of Combat 14.  

o Limb Injuries
Any Serious injury on the Arm/Shoulder
requires a fumble roll, and one to the Leg
(includes Hip) requires a stumble roll. Any
Grievous injury to a limb is an automatic
fumble or stumble and renders the limb
unusable. A wing/tail/tentacle is rendered
unusable if it receives a grevious injury.
A bipedal creature with one usable leg
can crawl unaided, or rise and walk with
the aid of a staff/crutch/etc. A quadruped
with three good legs may rise/walk, at half
effective Move. Unusable limbs become
usable again when they heal to M1.

![image](https://user-images.githubusercontent.com/74210758/102000122-c7d12480-3c98-11eb-8b1e-1b8c7053a055.png)

**Comment by scooper4711** [comment]
I think you've found an inconsistency in the rules. The rules say any *serious* injury requires a fumble roll. The table shows *any* injury to the arm requiring a fumble roll.
I think this is one for the forums.

**Comment by mrg67** [comment]
Huh.  Interesting.  I'll certainly look into this and post it in Harn Forum.

**Comment by scooper4711** [comment]
post the link to the topic here when you do. And perhaps post the link to this bug in the topic.

**Comment by scooper4711** [comment]
On this topic, a reminder text on the grievous wound that the limb is now unusable would likely be helpful.

**Comment by mrg67** [comment]
It seems this has been debated on the Harn Forum in the past, but I'm not convinced there was consensus:

https://www.lythia.com/forum/viewtopic.php?f=2&t=11502&p=151760&hilit=injury+table+fumble#p151760

Harnmaster 3 - Combat 14
AND
Harnmaster 3 - Injury Table
I would say these two references are technically not incongruent. Note that the limb injury rule in the sidebar on HM3 Combat 14 has an optional box in front of it, thus implying that, whereas the Injury Table forces fumble/stumble checks for ALL limb injuries, this sidebar optional rule narrows the rule to apply only to serious or worse limb injuries.

So, no errata needed regarding these two: either use the Injury Table (default RAW) OR the Option on Combat 14.

**Comment by toastygm** [comment]
So what I implemented was essentially the optional rule.  In the armor location, you may specify whether a fumble or stumble is a risk.  See the following:
![image](https://user-images.githubusercontent.com/73371093/102001057-86de0d80-3ca2-11eb-8013-5661d5114f2e.png)
However, if a stumble/fumble is called for, then I check how severe the damage was, and if it is an S2 or greater, a roll is requested.  If the damage is a G4 or greater, then it is automatic.

Based on the standard rules, I should simply always require a roll on any injury to any limb with a Stumble or Fumble risk.

I can add support for an optional rule that will only cause the roll on a S2 or greater, and an automatic failure on an G4 or greater.

I will make this change in an upcoming version.

**Comment by mrg67** [comment]
I actually kinda PREFER the way you have it setup now (the optional rule).

**Comment by scooper4711** [comment]
Likewise. Make sure the current functionality is an option.
