### ISSUE TITLE
bug: drag & drop doesn't update for non-linked sheet

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#167]
Setup:
* non-linked token
* open token sheet
* open Std Armor compendium
* Drag e.g. cloth cap from compendium to gear tab
* Note that the cloth cap doesn't appear in gear.
* close token sheet
* open token sheet
* Note that cloth cap appears in gear tab.

**Comment by toastygm** [comment]
I believe this is fixed.  Please review and close, or identify if the problem persists.

**Comment by scooper4711** [comment]
Verified fixed in 1.2.16
