### ISSUE TITLE
bug: layers for a hit location is editable.

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#173]
it's editable, but changes are ignored.
Make it display only.
Same goes for the entire Basic Armor Settings section. It should all be read-only.

**Comment by toastygm** [comment]
No, it is editable, but changes only take effect if there is no armor worn.

If there is even one piece of armor, then the values are overridden.

So it still needs to be editable, just be aware that if you create any armorgear, that will overwrite any values you input.

**Comment by scooper4711** [comment]
There are a couple times when you have input fields where the user's input is ignored. 
There's a flag you can put in of editable=false which I think would be a better UX for those occasions.
