### ISSUE TITLE
bug: cannot initiate enhanced combat from token sheet

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#174]
I can't initiate combat from a token sheet for a linked (or unlinked) token.
It says the token can't perform that action at this time.
However, if I drag the weapon to the hot bar and select enhanced combat, then it works.

**Comment by scooper4711** [comment]
(I checked - the game is not paused, combat is active, and the player has initiative.)

**Comment by scooper4711** [comment]
Interesting - it works for the gamemaster. Not for the owning player.

**Comment by toastygm** [comment]
Is this repeatable?  Can you tell me how to repeat it?

**Comment by toastygm** [comment]
I figured it out (I think).  Fix will be in the next release.
