### ISSUE TITLE
Question:  missile weapon ammo configuration

### ISSUE THREAD

**Issue by mrg67** [toastygm/HarnMaster-3-FoundryVTT#179]
No rush, but I was setting up the gear for one of my players, and realized I wasn't sure how to set-up missile weapons that have an ammunition component (i.e., bows, slings).  I have experimented with thrown weapons, and they are different, since you are throwing the entire weapon, like a shorkana.  In my mock combats, I see that each time the actor uses the thrown missile, the inventory number decreases.  But, what if  the player has a bow?  Where are the arrows stored, and how?

Anyway...some sort of guidance would be helpful.  Thanks.

**Comment by toastygm** [comment]
Thanks for asking; obviously this is something that needs to be made more apparent.  Generally, I suggest placing the ARROWS, BOLTS, STONES, or whatever the actual missile is under Missile Weapons.  That way, as they are used the amount goes down.

Note that if, for example, you put Arrows there, there is a place in the sheet where you specify what skill is associated with the "arrow".  You put in Bow (or Long Bow, Short Bow, whatever).  This makes everything work well.

So what about the bow itself?  I usually put the Bow under Melee weapons.  WHAT?  Well, you can think of it in this way: the bow can be used as a club (or maybe staff), and in that sense it is a melee weapon.  Alternatively, if you just want to account for its weight, and not use it as a melee weapon, you can make it a Misc Gear.

What about a Spear, which can be both thrown and used as a melee weapon?  I usually indicate this in BOTH the melee weapon and missile weapon areas.  As a melee weapon, I set its weight to zero.  That way, the weight all works out.  Throwing the spear reduced the number by 1, and the entry in the melee section just provides the indication of how to use it as a melee weapon.

Hope that all helps.

**Comment by mrg67** [comment]
That does help.  Thanks.  I'll test it out.

I was already configuring weapons, which are both melee and missile, the way you described.  I think it's a very workable way of doing it.
