### ISSUE TITLE
creature sheet should only have one number for each ability

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#185]
The normal actor sheet has both the base ability score as well as the effective score which takes the physical penalty into account.
Creature actors do not calculate encumbrance, and so should have only one number displayed.

**Comment by jpmcdonald** [comment]
Is a creature always such?  Can a troll not put on a piece of over-sized armor?  An orc or gargun?  Or should those always use the main actor sheet?  I often use "standard" characters for minor NPC's, particularly combatants. e.g. the ss-hm3npc.pdf file is an excellent resource for 'canon fodder', I suppose you could always use the actor sheet for these kinds of minor characters, if you define a creature as not being able to carry gear/use tools then perhaps that makes sens.  

However, even if physical penalty (Encumbrance) is not accounted for, injury penalty and fatigue should be and these also  impact the effective score, so I believe these should still be displayed.

**Comment by toastygm** [comment]
Agreed.  These will continue to be displayed.

Not a bug.
