### ISSUE TITLE
Standard Armor Configurations 

### ISSUE THREAD

**Issue by jpmcdonald** [toastygm/HarnMaster-3-FoundryVTT#189]
I've been playing with the new container items; love them by the way.  I'm curious if it would be possible to adapt them in a way to handle standardized armor configurations. (or clothing for that matter).  The attached image shows what I'm thinking.  It's certainly possible to group armors on the character sheet into an item but it's currently not possible to equip them; and thus their armor values don't show on the Combat tab.  

In addition, it would be great if prototype containers could be filled in a compendium, or on the items directory, such that you could choose for example one of the armors as shown below or a guildsman's pack with items appropriate to the guild as a start. 

If this were possible it would go along way toward quickly creating npc's on the fly; as you could drag and drop standard equipment and armor configurations onto a template character.  

![Screen Shot 2020-12-19 at 10 43 19 AM](https://user-images.githubusercontent.com/24255029/102694641-fb0b3a80-41e7-11eb-92f7-addb9d36ef0d.png)

**Comment by toastygm** [comment]
Well, now we are somewhat in a fork in the road.  As currently implemented, containers model a real physical container, not a logical grouping.  So, a container represents a "sack" of some kind (possibly a bag, a backpack, a small jewelry chest, etc.  Logically, if you put something inside the container, you can't possibly have it equipped.  So, I have implemented to immediately "unequip" any item placed into a container, and I don't allow it to be equipped while in a container.

What you are asking for is more like a logical "group of items", not a physical container.  You would like to be able to perform group actions on these items, such as carry them or uncarry them all as a unit, or equip/unequip them all as a unit.

So, I think that is really what you are asking for.  It is orthogonal to containers; the group of items could be spread across various containers or "On Person".  You want this grouping to even exist in the Items list and the compendium.

One way I might implement this is by having a single item be a "key".  Any item associated with the "key" would have their equip and carry status slaved to that of the key item.  You could make this key item a breastplate, or a bow, or whatever.

The second, related feature you want is the ability to take a group of objects from a compendium or item list and import them in bulk into a character.  That seems outside of what a "system" is designed for, and it seems to be closer to what a "module" would do.  It in fact sounds like a pretty nice idea for a module.  I don't think it would work for compendiums, but you could definitely create a module that would take a folder of items and import them as a group.  There might even be such a module already out there.  If not, it would seem to be a relatively simple module to create.

So, net-net: I won't implement pulling in a group of items (that is the job of a module, which is separate from HM3).  I may implement the concept of a "key" item.  Please let me know if this sounds like something you would use, or that handles your use case.

**Comment by jpmcdonald** [comment]
Upon further testing this works way better as is than I'd thought.  I just tested again and by equipping each piece of equipment before adding it to the grouping, it is added to the armor calculations in the combat tab.  (Which is what we want).  If you click the suitcase icon for the armor group it drops the weight and unequips the whole group dropping weight from encumbrance and protective values from the combat sheet.  This is mostly what you want.  

The other functionality of this is to allow players to have several remembered configurations for equipment, e.g. guises, one for formal court Tunic, Hose, broadsword, etc. one for war, full armor, etc. Knights, etc. wouldn't typically carry one and wear the other, they'd wear one and leave the other at home, camp, saddlebags, etc. It looks like your current implementation allows this, simply create two guise or dress logical containers and apply the appropriate armor and or clothing to each one.  Carry and equip each item before adding it to the logical grouping, and then carry/uncarry to switch between them. 

The concept of a module for importing kits sounds interesting.  Is your implementation of container items fairly standard?  It might be a small enough bite that I could take a stab at it.

**Comment by toastygm** [comment]
Yes.  I use the standard mechanisms for Items, including drag and drop.  So, you should be able to make a module for it.  The nice thing is that such a module could be used by others outside of just HM3, which makes it a pretty nice little module.

Has this question been addressed, and can I close the issue?

**Comment by jpmcdonald** [comment]
Yes. I think you can close it.

**Comment by toastygm** [comment]
I was just looking at the code, and it looks as if you can already do this.  Create a folder in the Items sidebar, put some items in it, and then **drag the folder** to the character.  It should create all of the items in the character.  No new module needed.

**Comment by jpmcdonald** [comment]
I will try this again.  I'm actually getting spotty drag and drop from the items directory.  It seems to work fine for the first couple of items, then works okay for an item or two (I drag the item, it doesn't appear to populate until you switch contexts on the character sheet (say from gear to skills) and back again, and then quits all together.  Drag and Drop seems to work better with prototype tokens than actual ones, though the behavior is still spotty.
