### ISSUE TITLE
EML is zero for new character

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#190]
version 1.0.3
Created a new character actor and input all abilities. I noticed that the skill bonuses in the table overview showed zero, even though I had input abilities. 
Editing each skill to enter ML, I saw that the SB updated.
However, the EML never updates from zero.
![Screen Shot 2020-12-20 at 12 09 58 AM](https://user-images.githubusercontent.com/1970249/102707431-1d3ca100-4258-11eb-9645-c34671768322.png)

[fvtt-Actor-Earl_Hemisen_Curo.json.zip](https://github.com/toastygm/HarnMaster-3-FoundryVTT/files/5720639/fvtt-Actor-Earl_Hemisen_Curo.json.zip)

No obvious errors in console.

**Comment by toastygm** [comment]
Is this reproducable?  How do I reproduce it?
