### ISSUE TITLE
Unable to drop onto character sheet after deleting container with items

### ISSUE THREAD

**Issue by jpmcdonald** [toastygm/HarnMaster-3-FoundryVTT#192]
I discovered this while exploring Issue #189 which should remain closed... However, drag and drop does not seem to be working for me from either the Std Armor Compendium or the Items Directory.  When I attempt to drag an item (often the third or fourth item) it ignores the drop.  Though it appears that closing and reopening the character sheet then displays the dropped item (sometimes).   I wonder if the sheet is just not rendering after the drop of the new item?

**Comment by jpmcdonald** [comment]
Note I see the same results when dragging and dropping skills, esoterics, etc.

**Comment by scooper4711** [comment]
are you dragging the same or different items? dropping the same item multiple times will increase the quantity count. May not be immediately obvious.

**Comment by jpmcdonald** [comment]
Different items.  Will try to confirm later this evening.

**Comment by jpmcdonald** [comment]
Okay, I did some testing on this and it appears that if you put items in a container and then delete the container with the items included, you can no longer drag and drop onto the character sheet.

**Comment by jpmcdonald** [comment]
I'm using VTT 0.7.9 with HM3 1.0.4 I've got modules Compendium Folders, Dice So Nice, The Harn Comprehensive Price List, Friends Foes, & Followers, Quick Insert, and TurnMarker modules running if that helps.

**Comment by toastygm** [comment]
Thanks, I'll check it out.

**Comment by toastygm** [comment]
In v1.1.1, I created a container on an actor, added a number of items to the container, then deleted the container.  I was subsequently able to drag new items from the compendium onto the character.  So, I'm unable to reproduce this problem.  Can you please confirm that this issue can be reproduced with the current version?  If so, please provide exact instructions to reproduce.

**Comment by jpmcdonald** [comment]
This is working properly with the current version.
