### ISSUE TITLE
Support for optional spell rules

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#196]
Support the optional rules where every spell is treated as a separate skill with a separate ML. The EML is based on the spell's ML and not on the convocation level.

**Comment by toastygm** [comment]
I have three words for you about this: data model change.

For something that is an optional rule, I'm gonna wait on this one until I
get a lot more interest in it.

**Comment by scooper4711** [comment]
That's fine. Mostly documenting that it's not supported now. And if you're reading this and want this feature, vote for it to indicate interest.

**Comment by toastygm** [comment]
At this point I have no intention of implementing this.

**Comment by ErnoRubik** [comment]
Our groups would also like to see this.  Our workaround for those that are interested: I'm using Data Toolbox to import "Individual Spell Skills" as custom compendiums.  Spells get listed under the Skills tab, under Magic (with the convocation skills) and it works fine.
