### ISSUE TITLE
change armor protection label

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#198]
the fourth armor protection should be "fire/frost", not just "fire".

**Comment by toastygm** [comment]
Read "Combat 5", last sentence under "Armour Aspects".
They only specify Blunt, Edge, Point, and Fire.
Nothing about frost.
Combat 13 talks about "flammable armor" as an optional rule.
The only place where I see it discuss Frost is in the Bestiary, where under "Skills and Weapons" it says the weapon aspects are ...and Fire/frost.
On the Armour Protective Values table, it has this weird little section: Squeeze=Blunt, Tear=Edge, Bite=Point, Frost=Fire.

Given all of this, I consider this very low priority, and questionable even then.  Should I mark Point as Bite as well?

**Comment by scooper4711** [comment]
This appears to be a holdover from HM2 / HMG.
