### ISSUE TITLE
Add Fire/Frost weapon aspect

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#199]
Some weapons do fire/frost damage, e.g. holy water against undead. Add the ability for weapons to do fire/frost damage. 
I mean, armor can already protect against it.

**Comment by toastygm** [comment]
None of the standard tables show Fire/Frost damage for any melee or missile weapon.  Therefore, I do not include it either.  It would seem that any such damage is outside the realm of the normal aspect system, on top of the melee or missile weapon damage.  For example, you might have a fire arrow, the arrow does impact damage, and then the GM would separately have you determine the fire aspect of the damage.

**Comment by toastygm** [comment]
So you fire a fire arrow at medium range, and have an impact of 7 + 2d6 for the arrow; you do 13 impact as piercing damage.  Separately, the GM rules that the fire does 5 fire impact; that would be separate from the piercing impact.

As I said, I am not aware of any melee or missile weapon that does fire or frost damage, and no B/E/P damage.
