### ISSUE TITLE
In warning dialog about not having meleegear or missilegear equipped, specify the attacker

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#200]
In the error message "your controlled actor does not have missilegear named X", specify the actor/token name.
Use case - as a GM, I will have multiple macros down on the hotbar. I may have pressed the wrong macro, OR I may think that one actor is attacking but it's another actor's turn.
Make the error message a bit more explicit so that I more easily can detect the second case there.

**Comment by toastygm** [comment]
Fixed in 1.2.8

**Comment by scooper4711** [comment]
Alternate problem - if the actor has the gear, but it isn't marked as carried. The actor can still shoot with that missielgear.

**Comment by scooper4711** [comment]
confirmed fixed
