### ISSUE TITLE
Dragging neutral spell from items sidebar changes magic school

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#204]
version 1.0.4 and FVTT 0.7.8
I had created magic spells and stored them in the side bar. Declared that they were for Neutral convocation.
When I dragged them over to an actor, who had Neutral convocation and one more, the spells changed to the other convocation.

**Comment by toastygm** [comment]
This should no longer occur starting with 1.2.8.  If a spell already has a convocation, and it is dragged to an actor, it will retain the convocation originally specified.  If the convocation is empty, then it will be given the first non-Neutral convocation found; if no non-Neutral convocation is found, but there is a Neutral convocation, it will be given that instead.

**Comment by scooper4711** [comment]
confirmed fixed
