### ISSUE TITLE
Question:  inserting images in item description tab

### ISSUE THREAD

**Issue by mrg67** [toastygm/HarnMaster-3-FoundryVTT#206]
Item > Description Tab > image icon

Brings up a dialog box "Insert/Edit Image" which has a line for "Source"

What is the correct way/format for entering image information in this dialog so that it displays in the Description text?

![image](https://user-images.githubusercontent.com/74210758/103328465-df850880-4a0d-11eb-8cda-7b9e7b49c613.png)

**Comment by toastygm** [comment]
"Source" is a simple pathname.  That pathname must be relative to your "Data" directory.  So, it all depends on where your picture assets are.  If you have created a subdirectory off of your Data directory, such as "Assets", then it needs to be a relative path to there.

Alternatively, it can also be an URL.

Ultimately, this is going to go into the "src=" part of an HTML "img" tag.  So anything you can put in a "src" attribute will work.

The "Alternative description" will show up as a tooltip when you hover over the image, mostly for accessibility purposes.

Width and height are the bounding.  You can also leave those blank, and it will attempt to use the entire width of the description.

**Comment by mrg67** [comment]
Ahhhh...relative to the Data directory.  That was the key bit of information that I was missing.  Thank you.
