### ISSUE TITLE
Weight of Quilt Gambeson is slightly off

### ISSUE THREAD

**Issue by Slithkanter** [toastygm/HarnMaster-3-FoundryVTT#212]
This is a Nit, but in my copy of HM3 the weight of a Quilt Gambeson is 19.5.  The weight currently listed in the Standard Armor Set in the Item Compendium is 19.8.

It is easy to workaround, just thought you might want to know.

**Comment by toastygm** [comment]
HM3 (version 3.5), Combat 4, under Quilt it indicates the weight is 19.8
<img width="267" alt="quilt-gambeson" src="https://user-images.githubusercontent.com/73371093/103569095-8db00880-4e7b-11eb-823f-f98b20b5fd8b.png">

**Comment by Slithkanter** [comment]
Uhg.  I hate it when values vary between rule versions.  It is also 19.5 in my copy of HM 2nd Edition.  Thanks for checking.
