### ISSUE TITLE
Apparent incompatibility with GM Screen

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#214]
The GM screen module used to work with HârnMaster, but now it doesn't.
The logic for determining even/odd rows in HârnMaster helpers.js seems to break when a journal or actor is included inside of the GMScreen.
I don't know if the fault lies with [GM Screen](https://github.com/ElfFriend-DnD/foundryvtt-gmScreen/issues/40) or with HârnMaster, so I've opened a bug with each.
```
helpers.js:82 Uncaught (in promise) TypeError: Cannot read property '0' of null
    at getGridElementsPosition (helpers.js:82)
    at HTMLSelectElement.<anonymous> (GmScreenApplication.js:273)
    at HTMLDivElement.dispatch (jquery.min.js:2)
    at HTMLDivElement.v.handle (jquery.min.js:2)
```

**Comment by scooper4711** [comment]
Ah - looks like helpers.js is a GM Screen file (I saw "harn" in the file path and thought it belonged here).

**Comment by toastygm** [comment]
No, "helpers.js" is not part of this system, that must be from the GM
Screen module.

**Comment by akrigline** [comment]
Found the issue, Harn chat cards use the same class name for elements as I was using (I will namespace mine more and this will not be an issue). Thanks @scooper4711 for the debug help.

**Comment by scooper4711** [comment]
Closing this one then. Thanks!
