### ISSUE TITLE
Bug:  automated combat rolls macro not launching

### ISSUE THREAD

**Issue by mrg67** [toastygm/HarnMaster-3-FoundryVTT#216]
Expected:
Drag combat icon from actor combat tab to macro bar slot
Choose Automated Combat from 'Select Weapon Macro' dialog
Weapon icon shows up in selected macro slot
During combat, click on icon in macro bar for valid attacker with valid target
Macro launches, enabling Automated Combat dialog in Chat window

Actual Result:
Everything as stated above except the last step.
Click on the button in the macro bar does nothing.

Note:  The Automated combat can be launched directly from the Actor's combat tab.

**Comment by mrg67** [comment]
I THINK that I found the issue.  The macros (by default) were not configuring so that they were "owned" by the actor.  Therefore, they could not be executed via the macro button.  I'm not sure why I wasn't experiencing this issue when I tested it previously.

**Comment by toastygm** [comment]
I'm having difficulty reproducing this.  Can you please open the console (press F12 on windows, or opt-cmd-i on mac) and then invoke the macro, and let me know if there is any error that displays?

**Comment by mrg67** [comment]
My apologies.  It was a macro permissions issue.  The ownership of the macro folder was set to none.  You can close this.
