### ISSUE TITLE
Automated Combat:  defensive choice of block not displaying results

### ISSUE THREAD

**Issue by mrg67** [toastygm/HarnMaster-3-FoundryVTT#219]
Attacker chooses a weapon
Defender chooses to Block and specifies a blocking weapon

Expected result:
dice are rolled against appropriate skills
chat window displays results

Actual result:
dice are rolled against appropriate skills
no results are displayed in chat window.
the defensive choice dialog stays in the chat window

if the defensive block choice is clicked for a SECOND time, then the dice are rolled again and the combat results display

**Comment by toastygm** [comment]
Is this repeatable?  Does it occur all the time, or only under some circumstances or for specific actors/weapons?

**Comment by mrg67** [comment]
I have gotten it to be repeatable under the following conditions:

Defense choice is BLOCK
When the attack/defend results are MS/MS
When the attack/defend results are MF/MF

When defense choice is DODGE, it doesn't seem to happen.
I haven't tested COUNTERATTACK.

**Comment by toastygm** [comment]
I performed an attack, and used the block defense.  Result was MS/MS.  Here is the output in the chat:
![block](https://user-images.githubusercontent.com/73371093/104782662-71448380-5739-11eb-8fee-dcb970f63d96.jpg)

So I don't see a problem, certainly not the same thing you are reporting.  I will attempt to see if I can get a MF/MF to show this problem, but can you confirm that the same problem happens with different actors or different weapons?

Alternatively, use F12 or alt-cmd-i to open the console and see if there are any console errors generated.

**Comment by mrg67** [comment]
I tested it again with different combatants and different weapons.  I haven't gotten any MS/MS table results  yet, but I have gotten several MF/MF results and the issue is still occurring.

Not sure if this will help you at all.

![image](https://user-images.githubusercontent.com/74210758/104785251-ebc3d200-573e-11eb-98b7-05510794b1ec.png)

**Comment by toastygm** [comment]
Thanks, that help a ton.  It pointed me directly at the bug.

For now, to work around the bug simply disable the "Weapon Damage" option in the system settings page, and it will bypass the defective code.
![sys-settings](https://user-images.githubusercontent.com/73371093/104787451-6e02c500-5744-11eb-988c-1e23ad618993.jpg)
