### ISSUE TITLE
Capacity calculation for containers

### ISSUE THREAD

**Issue by mrg67** [toastygm/HarnMaster-3-FoundryVTT#223]
Here is a screenshot of a container that is toggled ON (i.e., being carried).  It has a capacity of 15, and contains 6.15 lbs worth of gear.

![image](https://user-images.githubusercontent.com/74210758/104860772-9ecc3100-58e1-11eb-82e3-f8792e4582b2.png)

When I toggle the container OFF, for some reason the container capacity total says it's carrying 58 lbs worth of gear.

![image](https://user-images.githubusercontent.com/74210758/104860813-d33fed00-58e1-11eb-9add-7b614189b860.png)

In addition, the calculation of the two containers seems to be linked.  Clicking one of them on/off affects the capacity calculation of the other container as well.

**Comment by mrg67** [comment]
In this example, the Weight totals across the top of the tab appear to be correct, even when toggling the container on/off.

The canvas bag weighs 2 lb and has 6.15 lb of gear inside for a total of 8.15 lb.
The leather backpack weighs 8 lb and has 27.65 lb of gear inside for a total of 36.65 lb.

When toggling both containers off, the capacity information for each is
10/15 (incorrect)
10/40 (incorrect)
This doesn't make any sense.  Why would the total gear weights both drop to 10 lbs?

When the bag is toggled on, but the backpack is toggled off, the capacity info for each is shown as:
6.15/15 (which is correct)
7/40 (which is incorrect)

When the bag is toggled off, but the backpack is toggled on, the capacity info for each is shown as:
58/15 (which is incorrect)
27.65/40 (which is correct)

**Comment by toastygm** [comment]
So if I understand correctly, although the bag which is not carried has an
incorrect weight, the total carried weight of the character is fine,
right?  The main problem is that the uncarried container is showing the
wrong weight, but the actual weight of the carried items is correct?  I
want to know for sure, since in one case it is just an annoying
inconsistency, but if the actual carried weight is incorrect that will
affect encumbrance and penalties.

**Comment by mrg67** [comment]
Correct.  The Weight totals along the top of the Gear tab appear to be calculating correctly, and the PP decreases correctly when un-carrying the containers.

**Comment by scooper4711** [comment]
Confirmed fixed
