### ISSUE TITLE
Maintaining initiative order in the CT during a round

### ISSUE THREAD

**Issue by greybeardgunner** [toastygm/HarnMaster-3-FoundryVTT#225]
When an actor's initiative changes due to an injury or other circumstance during play, it is automatically reflected in the CT, causing confusion about what the correct turn order is for that round.  For example, if an actor suffers an injury, their universal penalty changes and this causes their initiative to go down.  Currently, this will cause them to drop down in the turn order, making it difficult to keep track of the original turn order.

Possible solution is to have the tracker stay static for the round and then on the new round, reshuffle actors due to changes in initiative.  May require a "next turn" button or function.

**Comment by toastygm** [comment]
I can't reproduce this.  So far as I can determine, initiative is determined at the beginning of each round, not in the middle of the round.  It is true that if you manually ask for a re-roll it will be re-determined, but unless you do that the order will remain static until the next round.
