### ISSUE TITLE
Gold Mode: Injury Level automatically "G"

### ISSUE THREAD

**Issue by TimoLemburg** [toastygm/HarnMaster-3-FoundryVTT#254]
Then entering a new injury you automatically get a "G" added to the IL. In HMG the injury level works like this: On the injury table the severity is color coded and leads to different amounts of IP. Minor wounds inflict 1D10 IP, Serious wounds inflict 1D10+10 IP and Grievous wounds inflict 1D10+20. 
I would recommend to just not record the severity in HMG and leave the prefix. If it is needed for some follow-up calculation just calculate it from the IP entered (<11 = Minor, 11-20 = Serious, 21-30 = Grievous).

![Gold Mode - Injury Level with leading G](https://user-images.githubusercontent.com/4639290/121799698-ce335f80-cc2d-11eb-9d68-14048d819d5b.png)

**Comment by toastygm** [comment]
I have fixed this, and it will go out in the next version.  I dropped the prefix letter, and I changed the heading to "IP" in HMG mode, and "IL" in HM3 mode.
