### ISSUE TITLE
Gold Mode: Healing Roll Target not correct

### ISSUE THREAD

**Issue by TimoLemburg** [toastygm/HarnMaster-3-FoundryVTT#255]
When clicking on the HR number in the Combat Tab of the Character Sheet I see a Target Value identical to the Healing Rate. As far as I know it tests "HR X Endurance" in HM3 and in HMG it is on of two choices (no default given by the rules):

1. CONDITION (Skill) + ( 5x HR ) - PP
2. Endurance (Attribute) x HR - PP

I don't know if checkboxes are a possibility in the healing roll window, if this had to be implemented as a setting or if the possibility to roll for Healing has to be dropped at all.

![Gold Mode - Healing Roll Target not correct](https://user-images.githubusercontent.com/4639290/121800016-c5438d80-cc2f-11eb-9397-850f1ba6ec7d.png)

**Comment by toastygm** [comment]
This sounds like an HM3 bug; I will fix that.  As for HMG, I will probably not change this; in the case of HMG, you will simply have to modify the target value, or simply ignore healing rolls completely and do it yourself.

**Comment by toastygm** [comment]
After researching further, this is calculated as "Effective Endurance" x HR.  "Effective Endurance" in HMG is CONDITION / 5 rounded to nearest whole number.

Note that in HM3 "Effective Endurance" is affected by PP; that's part of the calculation.  But in HMG it is not.  So this value is correct for HM3, but it is probably going to be incorrect for HMG.  So same result: I suggest simply ignoring it for HMG, and roll yourself based on whatever rules you want to apply.
