### ISSUE TITLE
Adding Barbarians

### ISSUE THREAD

**Issue by DustyGold** [toastygm/HarnMaster-3-FoundryVTT#266]
Any chance you'll add Barbarians details to the compendium of skills/invocations? I'm very new to Foundry-VTT so I'm uncomfortable offering to create and export to a Compendium as I'm sure I'll fail to include macros to activate invocations and similar bits.

**Comment by toastygm** [comment]
I have no plans to add additional compendiums to the existing ones for HarnMaster.  As you indicate, someone can certainly create a module containing the appropriate compendium packs to share if they want to do that.

However, for your own use you do not need to even do that.  You can create any "ad hoc" skills you want on a character, so if you want to add specific barbarian skills or other skills you can do so anytime.  If you have any questions about this, feel free to ask for help on the Discord.
