### ISSUE TITLE
Initiative not rolled on start of combat

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#275]
I'm pretty sure that when starting combat, it used to be in HM that initiative was "rolled" - i.e. round one everyone was in correct initiative order without the players or GM having to take any action.
This is no longer the case.
They are now place in a random order until you roll initiative or until round 2 when initiative is automatically "rolled".

![Screen Shot 2021-07-14 at 6 50 00 PM](https://user-images.githubusercontent.com/1970249/125710882-d4911ec4-29e1-4c8e-a42b-c7b9b85b2838.png)

**Comment by toastygm** [comment]
No, I'm pretty sure this is how it has always been.

This is pretty typical; you must roll initiative when combat starts, it
doesn't automatically roll it for you.  This is a FVTT pattern based on the
fact that is 99.9% of all games, initiative is rolled, not determined based
on attributes.  I even have to fake out the initiative mechanism; I state
you roll a 1d0 + your initiative skill.  What a hack.

I specifically added code to automatically re-calculate initiative on each
round, but it doesn't get called on the first round.

Tom.

--
*Tom Rodriguez*
*w:* www.casualinsight.com | *e:* ***@***.***
*LinkedIn:* www.linkedin.com/in/tomrodriguez
*Twitter:* @TomRodriguezCI <https://twitter.com/TomRodriguezCI>
