### ISSUE TITLE
BUG: GM doing self rolls hides cards which the player should see

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#281]
Steps to reproduce:
 * GM has self rolls set, player has public rolls set
 * Player attacks NPC
 * NPC defends with counterattack
 * Both roll marginal success
 * player does *not* see the outcome of the attack.
 * Player is *not* presented with the card to determine injury or perform shock/fumble rolls
![Screen Shot 2021-07-25 at 7 26 08 PM](https://user-images.githubusercontent.com/1970249/126929372-298546cd-542d-4e53-8cb0-6a1785752bdb.png)

**Comment by toastygm** [comment]
I will look into this, but I'm not sure this is in fact a "bug": it may be
expected/desired behavior.  If a GM has GM Private Roll specified when they
perform a roll, the roll is private; there is no way to override FVTT to
tell it to make the roll public instead.  The correct behavior is for the
GM to either not set the roll as a Private GM Roll, or if this is done
accidentally, then to change it to a public roll and re-roll.

**Comment by toastygm** [comment]
Based on the feedback I've received, and a review of the FVTT code, this is not possible.  If a user makes a setting, such as a "GM Blind Roll", there is no way for the HM3 system to override that.  It is necessary for the user to change their setting.

In this case, the GM needs to be informed that they are making blind rolls, so they can turn off the setting.

**Comment by scooper4711** [comment]
I suggest either Chat Message Accessibility Indicators or Chat Portrait - both add textual description to every roll to indicate if it’s a self roll, blind roll or GM roll.

**Comment by scooper4711** [comment]
Actually, Louder Whispers is the best plugin for this:
Here's a private GM roll attack when using Louder Whispers:
![image](https://user-images.githubusercontent.com/1970249/129933108-27622ef5-2869-479b-b175-83f21087f372.jpeg)
