### ISSUE TITLE
A/D values incorrect for Foot/Leg/Knee in compendium

### ISSUE THREAD

**Issue by mrg67** [toastygm/HarnMaster-3-FoundryVTT#283]
In the FVTT compendium for Standard Melee Weapons, the Defense modifier is +15

In the HM3 rulebook (COMBAT 3) the Defense modifier is +5

![image](https://user-images.githubusercontent.com/74210758/128070383-38d99184-cf25-46d5-bed1-f10c55eaa45c.png)

![image](https://user-images.githubusercontent.com/74210758/128070485-d4562a1f-ed6f-4177-a3df-650f6a0ee621.png)

**Comment by scooper4711** [comment]
eagle eyes!
