### ISSUE TITLE
Display WQ roll during enhanced combat

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#284]
When the optional rule for weapon quality is enabled, please display the WQ checks which are happening.

Currently, they happen in the background and you only remember that they're happening when someone's weapon breaks. 

Displaying a card showing that the weapon quality check is happening reminds players that weapon quality is a thing, it's a thing worth paying for and gives a little extra drama of "oooh! I nearly failed that WQ check!"

**Comment by toastygm** [comment]
Chat is already very busy during combat.  Do we really want yet another
chat message on every weapon attack?  The chat window is going to become
very cluttered.

**Comment by scooper4711** [comment]
Make it an option/setting. 
Or maybe include it in the current combat outcome card. 
Or both.
