### ISSUE TITLE
Active effect "injury level" affects un-injured actor

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#288]
Steps to reproduce:
1. create new actor
1. Give the actor 1 UP (e.g. with fatigue)
1. Add an active effect which adds -1 to Injury Level

UP is decreased from 1 to Zero, and PP too.

**Comment by toastygm** [comment]
What I think you are looking to achieve is that the Injury Level is floored
at 0; if they specify a modifier to Injury Level, and that modifier takes
IL to <0, then you want the IL to be set to 0.

Is that what you are requesting?

**Comment by scooper4711** [comment]
Yup. And we should check if the same issue exists for Eg fatigue
