### ISSUE TITLE
HM for two handed weapons applies only to Attack ML

### ISSUE THREAD

**Issue by jpmcdonald** [toastygm/HarnMaster-3-FoundryVTT#289]
It appears that for two handed weapons (those with an HM modifier) that the mod is applied to AML but not DML.   This appears to cascade into the EML as well.

**Comment by toastygm** [comment]
Note that there is no "HM" in the system.  Some time ago I determined that
the HM was simply a special case of a more general modifier, so I replaced
"HM" with a more general "Attack Modifier".  You can put your HM modifier
into "Attack Modifier", and it will apply for attacks.

I did not create a "Defense Modifier".  At the time, I did not see a use
case for a defense modifier, so it was not included.

Note that there is already an A/D value; these hand mode modifiers can be
put there instead as well.

Changing this at this point would require a change in the data model, which
I am reluctant to do unless there is a serious issue.  I suggest using the
A/D value for your specific situation unless there is a reason that won't
work.

**Comment by scooper4711** [comment]
Then the compendium for weapons has to be reviewed and any weapon with a hand modifier will need to have the DC modified to include the HM. 

And since it would be asymmetric to have HM applied via attack modifier for AML but via DC for DML, we should also remove the attack modifier for those weapons and include it in AC. 

And since including it there isn't quite as obvious we should also make two handed versions of those weapons for the compendium.

**Comment by scooper4711** [comment]
Oh - another thought. Rename Attack Modifier to Hand Mode or maybe Weapon Modifier and apply it to both AML and DML. 

No model change needed. Could even keep the name as attack modifier in the data model.

**Comment by scooper4711** [comment]
Yeah. I like idea #2 better. Less work.

**Comment by jpmcdonald** [comment]
I'll clarify; it is the value under Mod for an equipped weapon on the combat tab. I discovered this while looking at a Knight character with Lance.  The default value was -15 which is the HM penalty for a lance.  It looks like this carries over from some weapons and not others.  There is no value for spear for example.  In any event, the Mod value is adjusting what you are listing for AML but not for DML; I'm fine with whatever solution you come up; I'm just trying to understand how you are approaching it...

**Comment by jpmcdonald** [comment]
Sorry, no value for staff, the value for spear is the HM mod of -10.

**Comment by jpmcdonald** [comment]
Okay, I've given this additional thought and as I think about it I'm clearer now on the implementation.  I don't see that there is a need to make ANY changes to the HM3 rules module; the Attack Modifier field is clearly identified as such in the weapon item dialogue and is easily editable from that location.  

The Std. Melee Weapons compendium probably needs adjustment as it appears the HM mod is reading into that field and since it's an Attack Mod only, it shouldn't be loading there.  Probably an easier fix than changing the code, and something most GM's can handle as they import the weapons being used. 

I think where it should be is as an effect on each weapon.  (It's sometimes on and sometimes off) so it would make since to me that for a Bastard sword you would have in the compendium item a Hand Mode penalty that you could turn on and off based on whether or not you were using the Bastard sword in one or two hands.  Likely with a label "Bastard Sword Hand Mode" -10, which should adjust the Weapon Attack and Weapon Defense ML for that weapon only (if that's possible).  

The one thing I haven't tested is how effects apply to the different values.  What is the difference between "Melee Attacks", "Weapon Attack ML", and "Combat Skills EML"  for example?

**Comment by toastygm** [comment]
I'd rather not go into those details in a GitHub Issue; I'll message you separately on discord about this.  I think you're going down the right path though.

**Comment by toastygm** [comment]
The suggestion here is to use the "Weapon Attack ML" and "Weapon Defense ML" active effects to support this use case.  I realize there is a bug with the Weapon Defense ML, that is being fixed as part of Issue #291 .
