### ISSUE TITLE
Character Sheet only displays name and token

### ISSUE THREAD

**Issue by jpmcdonald** [toastygm/HarnMaster-3-FoundryVTT#3]
![Screen Shot 2020-10-26 at 8 08 21 PM](https://user-images.githubusercontent.com/24255029/97456678-130cbf00-1907-11eb-9f0f-4b482e6515e4.png)

Not sure if its something on my end/set-up or with the code, but character sheets (and others) all seem to only have two editable fields.  Name and an image for token or icon.  

I'm running latest version of VTT on MacOS Mojave 10.14.6

**Comment by toastygm** [comment]
This is a known issue with version 0.3.1, the result of a regression bug that was re-introduced.  Please upgrade to version 0.3.2.
