### ISSUE TITLE
Physical Penalty applied to stats in error

### ISSUE THREAD

**Issue by DustyGold** [toastygm/HarnMaster-3-FoundryVTT#300]
The encumbrance  (physical) penalty is taking points off of eyesight, hearing, voice, and smell. It's not applied to  Intelligence, Aura, and Will. Physical penalty should not be applied to stats, only Universal Penalty.
![Stat question](https://user-images.githubusercontent.com/86576601/131203409-3a4f59ed-f16f-46f5-ac50-0773961b7a9e.jpg)

**Comment by scooper4711** [comment]
# Skills 6
Universal Penalty (the sum of Injury and Fatigue penalties) is applied to ALL *attributes* when they are tested. When any non-physical *Skill* is tested, its EML is reduced by FIVE times the Universal Penalty"

**Comment by DustyGold** [comment]
This is physical penalty, which is NOT applied to attributes. "Physical Penalty, in effect the sum of Injury, Fatigue, and Encumbrance
penalties, is applied directly to PHYSICAL attributes when they are tested." Skills 6.

**Comment by scooper4711** [comment]
yup. I was copying the rule and page to make it easier to verify that this is a bug

**Comment by jpmcdonald** [comment]
I believe the fix for this is in actor.js lines 550 to 575. Eyesight, Hearing, and Smell calculations should be moved to the universal penalty section, and modified to adjust for data.universalPenalty instead of data.physicalPenalty

**Comment by toastygm** [comment]
fixed.
