### ISSUE TITLE
Effects tab filter is not working.

### ISSUE THREAD

**Issue by jpmcdonald** [toastygm/HarnMaster-3-FoundryVTT#301]
The effects tab filter won't filer anything.  I believe this is because the effects are listed by {{effect.data.label}} and the filter is a data.effectsNameFilter

**Comment by jpmcdonald** [comment]
The error is in base-actor-sheet.js

Line 472 should read: const effectName = effect.getAttribute('data-effect-name');

vs const effectName = gear.getAttribute('data-effect-name');

**Comment by jpmcdonald** [comment]
While the above code change appears in my testing environment to fix the filter, the feature is less useful than I expected.  Clicking on a filtered list item removes the filter; My hope was that by using the filter one could quickly get to the effects button to turn it on or off.  This appears to not be possible and looks like it's a function of the filter capability.

**Comment by toastygm** [comment]
I have fixed this, kind of.

There is a separate, wider problem that once you put in a filter, if you try clicking on "edit" the filter blanks out.  If you try it again, then it works.  There is some sort of race condition at work here.

Net result is that if you do it a few times, it should work.  It's not a great experience, I know, but that's the workaround for now.  I will open a separate bug to track that issue.

**Comment by toastygm** [comment]
fixed
