### ISSUE TITLE
Filter skills doesn't work on creatures

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#306]
steps to reproduce:
 1. import attached creature
 2. go to skills tab
 3. filter on any skill
[fvtt-Actor-count-mule-aca.json.zip](https://github.com/toastygm/HarnMaster-3-FoundryVTT/files/7110767/fvtt-Actor-count-mule-aca.json.zip)

**Comment by toastygm** [comment]
fixed
