### ISSUE TITLE
Damage roll dialog fails to display weapon name

### ISSUE THREAD

**Issue by toastygm** [toastygm/HarnMaster-3-FoundryVTT#31]
When you click on the weapon damage button, the dialog that appears shows "Weapon Name:" and the actual name is blank.  This should be the actual weapon name.

**Comment by mrg67** [comment]
Minor typo in Injury Results text.  "recieved" should be "received"
![image](https://user-images.githubusercontent.com/74210758/99153207-fb9a3980-265b-11eb-98e0-d8699e884b10.png)
