### ISSUE TITLE
Two DTAs in the same turn

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#314]
Discovered while testing combat in 1.2.23
Actor A got a MS blocking when Actor B had a CF on attack.
Actor A initiated a DTA attack
Actor A got a MF when attacking and Actor B got a MS.
This allowed Actor B to initiate a DTA attack.

Combat 12 states:

> If a second TA is generated in the same turn, by either party, it is ignored and the turn ends.

This is such a corner case, it's ok if you just close this. Thought you should know though.

**Comment by toastygm** [comment]
Yeah, I'm aware.  I've seen this happen a couple of times.  I'm not going to put in special code to deal with it though, the GM/Players will simply have to realize the second TA is not allowed by the standard rules.
