### ISSUE TITLE
Armour Quality not applied

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#316]
Combat 5:

> The Armour Protective Values table assumes average quality (+0) materials. Armour materials can be purchased at higher or lower qualities. The effect of these ratings (maximum +4) is to increase or decrease all protective values by the quality rating. That is, a +1 mail Hauberk has protective values of B3, E9, P6, and F2.

I applied an amour quality modifier and the calculated armor protection value isn't increased.

**Comment by scooper4711** [comment]
Honestly, not sure if this is a bug or an enhancement request since AQ was really never implemented.

**Comment by toastygm** [comment]
The AQ value is provided to allow you a place to record Armor Quality.
However, neither the Armor Quality rules nor the Weapon Quality rules are
implemented, nor do I have any plans to implement them.

You may work around this limitation by manually changing the impact rating
of the armor item itself as its quality increases or decreases.

**Comment by scooper4711** [comment]
Weapon quality is usually a two digit number like 12 or 14 and you have implemented the weapon quality rules as optional (weapon breaking). 

Armor quality is more like D&D: +1 magical armor or such.

Just thought I'd point out the difference. If you don't want to implement it that's totally valid. Just a little odd to have the input field there is all. Then you have to do armor quality in two places - well five places really. (That field, and one each for b/e/p/f)
