### ISSUE TITLE
Skill Improvement function not working

### ISSUE THREAD

**Issue by mrg67** [toastygm/HarnMaster-3-FoundryVTT#325]
Using the "star" to facilitate a skill improvement roll doesn't mathematically add 1 or 2 points.  Instead it tacks a "1" or "2" onto the end of the ML, resulting in MLs that are three digits.

Expected Result:
Click on star for a skill to highlight it.
Click on the same start again to start the skill improvement process.
Choose Perform SDR in dialog box.
If SDR fails, ML does  not change.
If  SDR succeeds, ML should be increased by 1 (or 2 if specialty skill).

Actual Result:
Click on star for a skill to highlight it.
Click on the same start again to start the skill improvement process.
Choose Perform SDR in dialog box.
If SDR fails, ML does  not change.
If  SDR succeeds, ML is previous ML, with a "1" tacked onto the right-hand side of the ML (a 2 if a specialty skill).

![image](https://user-images.githubusercontent.com/74210758/149561737-2f662bf0-c4cb-481d-b043-85981ca88788.png)

**Comment by scooper4711** [comment]
Confirmed as fixed in 1.3.0
