### ISSUE TITLE
Can't Create an Actor

### ISSUE THREAD

**Issue by pwdennis2** [toastygm/HarnMaster-3-FoundryVTT#334]
Just installed HM3 system 1.2.25 in FoundryVTT 9 build 242, no modules, and cannot create an actor. Create Actor button does nothing. Not sure how to provide more information for troubleshooting.

**Comment by toastygm** [comment]
HM3 1.2.25 is designed only for Foundry VTT 0.8.9 or below.  For Foundry VTT 9, please use HM3 v1.3.0.
