### ISSUE TITLE
Container Actor sheet needs to be closed and opened again to update inventory contents

### ISSUE THREAD

**Issue by AWD-2** [toastygm/HarnMaster-3-FoundryVTT#335]
Foundry VTT Version 9 Build 245
HarnMaster 3 1.3.0

Created a Container Actor sheet, tried dragging an item from another PC, from a Compendium, and from the Items tab.  In each case I had to close and reopen the Container Actor sheet to update it.  Tried this with no activated modules and had the same result.  Thanks.

**Comment by scooper4711** [comment]
Duplicate of #326
