### ISSUE TITLE
Injuries don't update the shockIndex resource bar

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#341]
Steps to reproduce
* Add an injury to an un-injured, un-fatigued actor. Specify injury level 4.
* Note that the shockIndex resource bar is not updated.
* Change the injury to injury level 5
* Note that the shockIndex resource bar is not updated.
* Add a singular fatigue point to the actor.
* Note that the shockIndex resource bar is updated to the appropriate value for a UP of 6

**Comment by scooper4711** [comment]
I think this is because fatigue is an attribute on the Actor, while Injury Level is an attribute on an Item (the injury) that the Actor possesses.

**Comment by toastygm** [comment]
While it is true that Injury Level is an attribute of the Injury item type, the total of all injuries is summed up into the "totalInjuryLevels" attribute of the Actor.  So your idea probably doesn't apply.

I did a short test, and it seems to work correctly.  I will have to test more.

**Comment by scooper4711** [comment]
Updated the title and description to reflect that it's the resource bar that doesn't update
