### ISSUE TITLE
Editing item in container moves it out of container

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#356]
I pulled up details on an item in a container and when I closed the details window, the item was moved to on person.
Dragging and dropping the item to the container, or editing the item and manually selecting the container both result in this error:

````
Error: You are accessing the HarnMasterItem#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly.
    at logCompatibilityWarning (commons.js:1685:19)
    at HarnMasterItem._logV10CompatibilityWarning (commons.js:6612:14)
    at get data [as data] (commons.js:6512:24)
    at base-actor-sheet.js:137:35
    at Array.map (<anonymous>)
    at HarnMasterCharacterSheet._onSortItem (base-actor-sheet.js:135:40)
    at HarnMasterCharacterSheet._onDropItem (foundry.js:60890:62)
logCompatibilityWarning @ commons.js:1696
````

**Comment by toastygm** [comment]
The problem indicated here with dragging items is fixed.  The issue with the moving item is a different bug: whenever you go onto a item form, it sets all dropdowns to the default values; the default for containers is "on-person", so whenever you edit an item it will move back to on-person.

Workaround is to set the dropdown TWICE.  The first time it will go back to default, the second time the value will stick.
