### ISSUE TITLE
Creature Actor - Weight not being tallied/changing encumbrance

### ISSUE THREAD

**Issue by greybeardgunner** [toastygm/HarnMaster-3-FoundryVTT#363]
Adding gear on the Creature Actor sheet does not tally, nor does it effect Encumbrance.
![Capture](https://user-images.githubusercontent.com/77867508/197859969-4aaf44d1-52f4-4cb9-b373-8a1611a6fe61.PNG)

**Comment by greybeardgunner** [comment]
![Capture](https://user-images.githubusercontent.com/77867508/197860428-77c8c63b-8dfb-4696-9d16-360f13b8ebe7.PNG)

**Comment by toastygm** [comment]
fixed in 1.4.5
