### ISSUE TITLE
Missile Weapons on CS not applying A/D modifier from Melee Weapons

### ISSUE THREAD

**Issue by greybeardgunner** [toastygm/HarnMaster-3-FoundryVTT#364]
In example image: Bow has AML/DML of 76/76 (base EML of 71 plus 5/5 modifier for Bow)
Heavy Arrow in Missile Weapons shows AML of 71.

![Capture](https://user-images.githubusercontent.com/77867508/200442781-34646e14-a193-4455-9680-641e963cffb0.PNG)

**Comment by toastygm** [comment]
This is intentional.  The value shown for Bow for Melee is when the Bow stave is used as a melee weapon (to use as a makeshift staff).  In that case, the A/D value applies for use of the bow stave as a melee weapon.

In the case of use of a missile weapon with arrows, the arrows have no A/D value.
