### ISSUE TITLE
Can´t create any effects

### ISSUE THREAD

**Issue by Ermine09** [toastygm/HarnMaster-3-FoundryVTT#375]
I can create a new effect itself on effect tab in character sheet, item sheet etc., but I am not able to add any active effect into it and clicking on plus button next to the Effect Value does not do anything.  
![Effect issue](https://github.com/toastygm/HarnMaster-3-FoundryVTT/assets/96796028/00a0c241-d2cf-43a2-b857-3129cd8c654d)

**Comment by toastygm** [comment]
Fixed in 1.5.2
