### ISSUE TITLE
Actor biography tab not saving

### ISSUE THREAD

**Issue by mrg67** [toastygm/HarnMaster-3-FoundryVTT#43]
Expected behavior:
1. open actor sheet
2. go to biography tab
3.  click on edit button
4.  make edits
5.  click on Save button
6.  entered values are retained

Actual behavior:
6.  entered values are not saved

**Comment by toastygm** [comment]
More information:

If you make a change to the Biography editor, then make changes in the Description editor (on the Profile page), both text changes are saved.

If you only make a change to the Biography editor, the changes are not saved.

If you only make changes to the Description editor, the changes are saved.

So the only time this doesn't work is when only the biography is changed.

**Comment by toastygm** [comment]
Be sure to click on the save icon to save your work in the editor. See attached graphic.
![editor-save](https://user-images.githubusercontent.com/73371093/99199852-d76f5300-2756-11eb-92a6-70b78fa6448c.jpg)

**Comment by mrg67** [comment]
Thanks for the guidance.  I'm messing around with it, and appear to be able to save changes in both Profile and Bio tabs now.

**Comment by toastygm** [comment]
Ok, then I'm closing this issue as resolved.
