### ISSUE TITLE
Delete button "lock/unlock"

### ISSUE THREAD

**Issue by mrg67** [toastygm/HarnMaster-3-FoundryVTT#44]
Issue:  it is very easy to mistakenly click the delete (trashcan) button on the Skills, Combat, and Gear tabs.  Since there is no verification message about intent, accidental deletion of skills or items is a risk.

Recommendations:

1.  a toggle near the top of the column where the edit and delete buttons are which would lock/unlock the delete function

or...

2.  an "are you sure" popup dialog whenever a delete button is clicked

**Comment by toastygm** [comment]
I added an "Are you sure?" dialog box when someone clicks on the delete icon for any item.  This will go out in the next release.
