### ISSUE TITLE
Enable Weapon Damage roll against Weapon Quality value

### ISSUE THREAD

**Issue by mrg67** [toastygm/HarnMaster-3-FoundryVTT#45]
Recommendation:
Enable the WQ column of the Melee Weapon list in an actor's Combat tab to be a "rollable" value.

![image](https://user-images.githubusercontent.com/74210758/99191765-a6c1f600-2723-11eb-8965-f256d247c428.png)

Result should be visible in the Chat Log.
See Combat 12 sidebar of HM3 rules.

Optional:
If you really want to get fancy, I guess a failed Weapon Damage roll could also result in the broken weapon's WQ value being automatically populated with a zero value and being unequipped.

**Comment by scooper4711** [comment]
Implemented in 0.7.18
