### ISSUE TITLE
Make Equipped and Carried icons more visible

### ISSUE THREAD

**Issue by mrg67** [toastygm/HarnMaster-3-FoundryVTT#46]
Recommendation:
change status colors (black = Y, grey = N) for "Carry Item" and "Equip Item" to something that stands out more.

recommend Green =Y and Red = N

**Comment by toastygm** [comment]
I have decided not to include those colors; I don't really think adding colors to those icons fits with the look of the character sheet.  But what I have done is to make the default icon and text state dark, so they are more apparent, and the "inactive" state greyed out.

When an item is marked as not carried, the entire line's text is greyed out (except the edit and delete icons).  That should make it more apparent when an item has been marked as "not carried".
