### ISSUE TITLE
Add wound/injury Type to INJURIES section of Combat tab

### ISSUE THREAD

**Issue by mrg67** [toastygm/HarnMaster-3-FoundryVTT#47]
Recommendation:  record aspect type that caused injury to be recorded in INJURIES table.

The INJURY dialog box requires the user to input the Aspect of the weapon (potentially) causing the injury.
![image](https://user-images.githubusercontent.com/74210758/99192193-77f94f00-2726-11eb-8bc7-7768ebb9b7bb.png)

If the resulting injury is going to be automatically added to the Character Sheet, why not record the injury "type" as well so that information doesn't get lost/forgotten for post-combat treatment purposes.
![image](https://user-images.githubusercontent.com/74210758/99192179-58fabd00-2726-11eb-8336-c6f58df9aebe.png)

Optional:  incorporate logic to convert Aspect value to injury "type"
Blunt:  Bruise (minor), Fracture (Serious), Crush (Grievous)
Edged:  Cut
Piercing:  Stab
Fire:  Burn

**Comment by toastygm** [comment]
How about a compromise?  Everyone loves a compromise. :) If you add a new injury manually, feel free to name it however you like, for instance "Thorax Bruise" or "Right Elbow Compound Fracture".  Sky's the limit.

What I will do is for the Injury roll, when I automatically add the injury, I will add the wording you suggested above.  It will be "Thorax Bruise" or "Left Upper Arm Fracture" or "Right Hand Stab", etc.

This won't require changing the data model, and it seems in line with what you want anyway.

**Comment by mrg67** [comment]
I hope you realize that all of my suggestions are just that...and pretty uninformed as well.

I like your compromise.  It provides the "aspect" part of the injury without becoming overly burdensome.
