### ISSUE TITLE
Checkbox to track skill development roll

### ISSUE THREAD

**Issue by mrg67** [toastygm/HarnMaster-3-FoundryVTT#49]
Recommendation:
For purposes of character management, provide a small checkbox or radio button that indicates a skill development roll (HM3, SKILLS 7) has been awarded by the GM.

It is not necessary to automatically execute the Skill Development roll...merely an indication that one is pending.

Options:
1.  checkbox appears on the SKILLS tab, as an additional column
2.  checkbox appears in the individual skill item itself

![image](https://user-images.githubusercontent.com/74210758/99193746-df67cc80-272f-11eb-851e-c451dae3b641.png)

![image](https://user-images.githubusercontent.com/74210758/99193762-fb6b6e00-272f-11eb-97bd-f3b2e7ed7b8b.png)

**Comment by toastygm** [comment]
So how would this work?  Let's say a GM decides the character should be awarded a SDR.  They go to the character sheet and the desired skill and click the checkbox.  An icon then appears for the character on that skill indicating a SDR is available.  How does that SDR indicator go away?  Does the GM have to go in again and turn it off?  Can only the GM set it, but the character owner can disable (un-set) it?

Let me think more on this.  This starts bordering on where I think the GMs should be managing this stuff outside of the character sheet, but I will consider it.  Sometimes dealing with this stuff in the system is more cumbersome than having the GM or character just note it down somewhere (for instance in a skill note)

**Comment by mrg67** [comment]
I agree that this is a minor thing that is a good example of diminishing returns.  I'll just ask my players to shoulder the very small burden of keeping track of it themselves; whether it's on a post-it note, or in the skill item notes.

**Comment by jpmcdonald** [comment]
I've given this thought and in paper games typically have players put a dot in front of any skill that has been developed. At the end of the game month, Any skill without a dot is subject to decline.  It's a pain to do this book-keeping.  I've changed my approach.  Players are encouraged to include their SDR's (and practice/training/study time, etc.)  in their player journals.  No entry in the journal means your skill suffers decline.  It encourages players to keep journals.  

An alternative could be to use the image currently set to the mystery-man.svg file to be either an open circle or a filled in circle to indicate the protected status or SDR roll award.  

If you are going to do anything with this, I'd rather see the SDR be made either with a roll-over die on the SB or ML column and automatically upgrade ML if successful.

**Comment by toastygm** [comment]
Doing any of this will require changing the data model for the character and creature actors, which I don't generally take lightly; it requires a migration to get it to work correctly with existing characters.  It will be necessary to decide how important such a feature is (is it worth the work/danger involved in a migration).

In the meantime, I have modified the character sheet to display the notes for the individual skills.  For now, you can always include a short note, such as "SDR", for each skill to remind yourself that an SDR is available.  This is the simplest approach that doesn't require any modification of the data model.

Will this approach (using the notes) work for this use case?

**Comment by toastygm** [comment]
Ok, it sounds like the notes approach will work.  I am going to close this for now and we can revisit in the future if the notes mechanism doesn't work.
