### ISSUE TITLE
Inventory Management in Actor sheet

### ISSUE THREAD

**Issue by mrg67** [toastygm/HarnMaster-3-FoundryVTT#50]
Recommendation:

- The ability to create items in the Miscellaneous Gear section of the GEAR tab on the Actor Sheet that represent "containers" such as bags, sacks, boxes, chests, pouches.
- The ability to organize other items in the Miscellaneous Gear section so that they are represented as being inside of these containers.
- Drag/Drop capability between containers
- Clicking the Carry/Equip status buttons for containers applies to everything within/inside those containers
- The ability to collapse/expand the view of a container folder

I don't really know what the capabilities of the actor sheet are, so I'm just looking for an improved way to manage inventory.

**Comment by toastygm** [comment]
What you are looking for is not easy.  Actors contain items, but there is no way to create an item that contains other items.  So there is no way to have a character have a bag, and there are things inside the bag.

I could get really tricky, and start adding flags to items that indicate whether to display them on the sheet if they are "associated" with another item; but I hesitate to go there.  That way heads towards madness...

For now, you can always use the notes to indicate whether an item is in a backpack or whatever.  It is not automated or elegant, but it would work if you need that.  Here's the rub: if you want a "sack", and you want to be able to drop the sack and have someone else pick it up (with everything in it), that sack is going to have to be an actor so it has independent existence from your character.  And actors cannot contain actors.  So, the problems here rack up quickly.

**Comment by mrg67** [comment]
Having you spiral in to madness will not be a benefit to anyone!  I see the complexities as you have described them.  It's not a huge deal, and so-far, I haven't really pushed my players to be over concerned with exact inventory management.  I can foresee a day when Foundry maybe updates their API to more easily implement such tricky functionality.  It's not worth it at this point.

**Comment by toastygm** [comment]
See the comments in issue #51 .  For now, I am going to close this issue as it is related to that one.
