### ISSUE TITLE
New Actor type to represent group gear

### ISSUE THREAD

**Issue by mrg67** [toastygm/HarnMaster-3-FoundryVTT#51]
Recommendation:
Adding a new actor type (besides character or creature) to facilitate situations like a group of PCs with shared items/resources/loot.  I.e., a ship's hold, a loot chest, a lodging, a pack animal.

Items could be seen by all PCs with appropriate permissions.

Items could be dragged-dropped between the "Inventory" actor sheet and a "character" actor sheet.

This could be as simple as re-purposing a character type, and stripping out everything except Biography and Gear, though I'm not sure if that would require a change to weapons...as they normally are stored/displayed under the Combat tab.

It seems like this is a common type of request, with a number of solutions for other game systems already out there.  I did try to integrate them into the HarnMaster system, but they don't seem compatible.

https://github.com/jopeek/fvtt-loot-sheet-npc-5e

https://github.com/SvenWerlen/fvtt-loot-sheet-npc-pf1

**Comment by toastygm** [comment]
Thanks for the suggestion.  I actually looked at this whole thing some time ago, but I deferred it until I got the basic character/creature sheets working.  Now that all of that is pretty wrapped up, I can consider this.

The general problem is to create a sort of "container"; in the current system, an Actor is the only thing that can contain items, so it would have to be a new sort of actor (as you correctly suggested).  The container could represent a chest, or a cart, or possibly even a shop with items for sale.  There is much that distinguishes this from Characters and Creatures: it does not have ability scores, or endurance, or any other feature like that.  It simply contains items.

Let me continue to think about this a while before committing to a particular approach.

**Comment by jpmcdonald** [comment]
So I've played with this some.  I think the way you have it now for container items works reasonably well.  It does require some editing on the fly, but not too much.  The image below shows how I've done it.  

![Screen Shot 2020-11-15 at 11 34 01 PM](https://user-images.githubusercontent.com/24255029/99216600-a7966e80-279b-11eb-946f-ccd4032c6749.png)

So Braelyn's Knapsack contains several items that he may need from time to time, but he likely will not bring with him into combat. Getting something out of the backpack requires a Grope action (in game).  The mechanics of the record keeping can easily be done in one of two ways:

1.) force the player to edit the Knapsack item by clicking on the edit icon to open the editor, Select the item, take out the item by changing the text style to strike through, editing the weight fo the knapsack, closing the item and then click the carry item button (and equip item) for whatever was removed.  While this is a bit fiddly, it has the advantage of when you want to drop the knapsack, you only have to click the carry item icon for the knapsack and all it's contained item weights are dropped with it.

2.) Keep the item weights separate and just click equip item when the player takes the item out.  This is easy for removing/putting an item back into a container.  It has the disadvantage of requiring you to click the carry item icon for both the container and all of the items in it when the character decides to drop the knapsack.  

Chests, Shops, Carts, etc. can easily be handled with a table in either a misc. Gear Item or a Journal.  The one I'd like to see (someday) is a vessel profile re: Pilot's Almanac.  Probably not a lot of demand for this though.  

Appreciate any thoughts on this approach to containers.

**Comment by toastygm** [comment]
I really like your approach to this; it's novel.  I think you outlined two different ways to make this work with the current mechanisms.  Personally I would probably just keep track of everything separately and drop things individually, but others might want to do things differently as you suggest.  Excellent!

In some other systems, particularly D&D5e, they support a "vehicle" actor.  I haven't really investigated this too much; but I may do so.  The idea would be to be able to model any sort of vehicle, presumably that can carry both actors and/or items.  Carts, wagons, ships, etc. Maybe even a horse could be considered a sort of vehicle for game purposes.

The other idea is for a "container" actor.  This is an entity that does not have living characteristics (i.e., ability scores) but does have the ability to associate items that has an existence apart from the characters.  For example, a chest or a house or a store might be this sort of actor.  You could add and remove items from such a thing.  It has a different purpose from the container you are mentioning (you wouldn't generally carry this sort of container on your back).

Those are some of my thoughts right now.

**Comment by mrg67** [comment]
I like JPMcdonald's ideas...though the more I think about it, I can't really decide on which one I feel would work most smoothly.  I guess I'd just leave it up to each individual player to make that decision for themselves.

I really AM sold on the idea of "container" and "vehicle" actors though.  I might just go-ahead and use a character actor and ignore all of the parts/tabs that don't really apply for that use-case.

Thanks for all you guys do to make this a constantly improving platform!
