### ISSUE TITLE
Where to save image files?

### ISSUE THREAD

**Issue by jpmcdonald** [toastygm/HarnMaster-3-FoundryVTT#53]
Not sure this is really an issue, maybe more one of documentation.  When I upload an image file into the system I get a warning that it's unsafe to do so because it will be over-written when I update.  This seems to happen; though it's inconsistent.  (I may be storing them inconsistently...)

Where should I (safely) store my assets directory, and where should they be uploaded when adding them as a map, to an actor or item sheet, etc.

**Comment by toastygm** [comment]
I believe the warning you are receiving is:
> You have uploaded files into a module or system directory. This is generally unsafe because updates to the system or module will delete your files.

Generally when you click on an image you get the file picker dialog box which will start at the "Data" directory.  Under the data directory there are three pre-defined subdirectories: "worlds", "modules", and "systems".  The modules directory are where modules are kept (such as my "Friends, Foes, and Followers V1" module), and the system directory contains the systems (such as "hm3", which is the HarnMaster 3 system).  When you perform an upgrade of modules or systems, it is possible for items in these directories to get wiped out.

It is much better for you to either:

1. Create your own assets directly under the "Data" directory, or
2. Create a directory in your specific "world" directory.

The benefit of creating it in your world directory would be if you want the assets to be only associated with the particular "world" you created.  For instance, you might have one world created for each campaign (then you will find each world has its own subdirectory under the "worlds" directory); in that case, keep the assets for each campaign in that specific world directory.  That way if you backup your world directory, the assets get saved with it.

But if you have assets you want to use across separate worlds, maybe icons or such, then put them in a subdirectory directly under the Data directory.  That way it saves space if it is used across multiple worlds.  But if you do that, be aware that if you backup any specific world you won't backup those assets.

Hope this all helps.
