### ISSUE TITLE
Unable to drag/drop skills and weapons to macro bar

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#58]
This appears to be a regression with the latest version.

**Comment by scooper4711** [comment]
applies to dodge, injury etc rolls too.

**Comment by toastygm** [comment]
What are you looking for this to do?  Do you want to drag the skill to the macro bar, and be able to make a skill roll from the macro bar?  For weapons, which roll would you want (Atk, Def, Damage)?  For missles (Atk, Damage)?

Note that items such as the Injury, fumble, stumble, shock, etc., are not "items", so they can't be dragged to the macro bar.  The only things that can be dragged are Skills, spells, invocations, armor locations, injuries, missiles, weapons, armor, and misc items.  Nothing else can be dragged.  I would need to know what single action needs to be performed by the macro.  Can you provide some suggestions (skills, spells, and invocations only have one roll so they are obvious, but the others aren't).

**Comment by scooper4711** [comment]
I'm reasonably confident that this used to work. I dragged a weapon to the macro bar, and when I pressed it, it asked me which type of roll to make - attack, defense or damage.
Having selected one of the three buttons, it proceeded to roll that roll, including asking what aspect of the weapon (edge, blunt etc)

**Comment by toastygm** [comment]
So no, that never worked.  I have never supported the macro bar before, and I'm certain there is no way it would have worked without me coding something for it.  You must have seen it somewhere else.

Regardless, I have now implemented this in 0.7.4.
