### ISSUE TITLE
Select all when tabbing into abilities

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#59]
When tabbing into abilities, e.g. str, sta, dex, sometimes the browser will select all the number (initially zero), sometimes not.
When adding a new actor, if you're not paying attention, you end up with a STA of 150 instead of 15. 
If you just tab from field to field, it behaves correctly. But if you enter text, when you tab to the next field it briefly highlights the text then it de-selects the text and puts the cursor at the front of the field.

**Comment by toastygm** [comment]
I don't think I have any control over that.  I will investigate, but I may not be able to fix this issue.

**Comment by scooper4711** [comment]
Fixed in 0.7.18

**Comment by scooper4711** [comment]
https://gitlab.com/foundrynet/foundryvtt/-/issues/4280
