### ISSUE TITLE
Add all standard attributes to Profile page

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#63]
The following attributes are standard (and oftentimes rolled for) but currently managed via a large text box. It would be better to have them as fields. No, you never "make a height check" so we don't need dice, but making them fields makes it so that they don't get skipped. Piety may have use in an API. The others, if you don't add them as fields, at least add them to the prompt.

- Piety (with fields for more than one god)
- age (or birthdate, with somewhere in the world to track the current date)
- height
- frame (which could impact armor prices)
- weight

Augment the rich text prompt to include:
Appearance (e.g. eyes, skin, hair):

**Comment by toastygm** [comment]
I originally had these as specific fields.  I chose intentionally to remove them in favor of the text box.  There are a variety of reasons, but they it all boils down to the fact that all of those items are descriptive; they do not have any effect on the software.  I don't perform rolls, or automatically modify values, or perform any other activity with them.  Therefore, they are purely descriptive and I choose to have them only available via a description.

The major benefit is if you want to add a new field to track, all you must do is modify the description!  No software change needed.

I can update the default text to include prompting for those items (eyes, skin, hair).

**Comment by scooper4711** [comment]
Piety can be added to any skill roll, so it could be included on the standard roll dialog and add to the situational bonus while subtracting from the piety attribute.

**Comment by toastygm** [comment]
Given the explanation, I am going to close this issue "as designed".
