### ISSUE TITLE
Ability to enter custom target location table

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#66]
This may be there and I'm not seeing it.
Not all Actors are human. They have different target location distribution.
Allow the end user to edit the target locations and their probabilities of being hit.

**Comment by toastygm** [comment]
Thats already there.  You can add new locations, or delete existing ones.  For those that you create, you can either base them off one of the default location types (head, neck, etc.) or you can go "custom" and define all parts as you like.
