### ISSUE TITLE
include player and skill icon when rolling

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#74]
Compare the chat dialog of "Turn Marker" with what we output.
In addition to the Actor's name, it has the token image.

It would be nice, since we're putting effort into associating images with everything, to display the images in the chat.
At the least, include the skill image
you may want to play with including the token too. But since I use Turn Marker, we have that right above anyway.

**Comment by toastygm** [comment]
I have no plans to include the skill icon in the chat window at this time.
