### ISSUE TITLE
Compendium for spells from the unofficial books on Lythia.com

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#75]
Create a compendium with unofficial spells from https://www.lythia.com/?s=unofficial+spells&post_type=post

**Comment by toastygm** [comment]
This sounds like a great idea!  Can you help?  If you can create a list of those spells, and then export it to a compendium, I can tell you how to send me your compendium so I can include it.

**Comment by toastygm** [comment]
I am in the process of putting together a module with a "kitchen sink" of compendiums for various items from Lythia.com.  This will not be part of the HarnMaster system itself, but will be separate add-on modules.

For this specific request, I will not be adding these compendium packs to this system itself.  You may always create this content and distribute it via a module.
