### ISSUE TITLE
Enhanced combat

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#76]
If a token targets another token (double-right click) and then performs an attack action (rolls AML), the player/gm controlling the targeted token should be prompted to select dodge, counter attack (and further selection of weapon) or ignore.
once the results are known, a roll is made on the impact table and an injury assigned.

**Comment by jpmcdonald** [comment]
This should probably be done via a macro and not implemented through the character sheets.

**Comment by scooper4711** [comment]
Fixed in 0.7.18
