### ISSUE TITLE
Record opportunity to improve skills

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#77]
When a player rolls a critical, they have the opportunity to improve that skill at the end of the session.
This is sometimes hard to remember.
Have a mechanism whereby skills rolls which are critical success or failure are automatically recorded as an opportunity to improve. Ideally, include the improvement roll capability
Ideas for how to record this:
 - checkbox next to a skill
 - appending the skill name to a text field
 - collecting the skill in a hidden field which controls which skills are presented for improvement in a later workflow

Ideas for how to manage the improvement roll
 - a button next to each skill
 - a single button which presents a list of all skills
 - a single button which presents a list of skills you have had a critical success/failure with.

**Comment by jpmcdonald** [comment]
I like this additional feature; I won't use it in the way that it was mentioned here though.  These are minor points, and GMs' just do things differently.  First, the stressful bonus experience rule is subject to GM discretion, as are many things, the granting of a development roll on a critical is a common house rule that I have used in the past.  I tend to grant the roll immediately; so there is no need for the star toggle.  However, the star toggle could be used in lots of different ways; 

I'll use it to mark skills as protected from skill decline.
