### ISSUE TITLE
bastard sword handedness

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#78]
Bastard sword can be wielded in two ways (hence the name apparently). One handed (with a -10 modifier) and two handed (no modifier)
The Compendium should list both as separate weapons.

**Comment by jpmcdonald** [comment]
I disagree.  A Bastard sword is a Bastard sword. it is one item.  If you wield it one-handed the penalty applies, if you wield it two handed it doesn't.  That's what the HM penalty is for.

**Comment by toastygm** [comment]
The problem with Hand Mode is that using it requires that the user declare at attack time whether they are using it one-handed or two-handed.  This then requires that the system pop up a dialog box asking whether to use one-handed or two-handed.  This ends up being clumsy in practice.

The more general approach, and what I have decided to do, is to replace "Hand Mode" with "Attack Modifier".  In this case, there will be two Bastard Swords: Bastard Sword 1H and Bastard Sword 2H.  The 1H version will have a negative Attack Modifier, while the 2H one will not.  You will display both on the character sheet.

This has the benefit that this same attack modifier can be used for other things too, including improved weapons (or inferior ones), magic, etc.

**Comment by toastygm** [comment]
This has been implemented in 0.7.5.
