### ISSUE TITLE
Add fields for spells

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#82]
Many spells have the following attributes:
 - Bonus Effects (rich text)
 - (Casting) Time - a formula based on CSI
 - Range - a formula based on CSI
 - Duration - a formula based on CSI

Very cool would be if you could integrate with Turn Alerts module if it's installed to add an alert for when the spell is done.
Perhaps just allow for a macro body which executes on success. Such a macro could also be used for adding special effects on the VTT

**Comment by toastygm** [comment]
I am going to close this as "will not implement".  There is no computational purpose to having all of these as separate fields, and it increases the complexity of the code to do so.  All of this information can be tracked in the notes or description.

However, I will be implementing a templating/formula mechanism where I will replace formulas in the notes field with the calculated value when the note is viewed (such as in a chat card).

I will also implement a Macro feature which will invoke a macro when an action occurs, such as a roll succeeding or failing.
