### ISSUE TITLE
When adding default skills, add default formulae

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#84]
When adding the default skills, also add the default formula for that skill

**Comment by jpmcdonald** [comment]
@scooper4711 do you mean the default SB formula or the OML formula, or both? 

@toastygm  this seems to be in conflict with the early discussion we had about this NOT being a tool for character creation. There were valid reasons for that.  There are complexities involved, going down certain paths can thwart flexibility, etc.  I'm not set on one or the other, but there are some design considerations here to think about.

**Comment by scooper4711** [comment]
I mean the SB formula. 
However, since we now have the skills compendium and it includes the formula and improved data entry method (it opens the dialog for you where you can enter ML when you drop the skill), this issue isn't as important. 
Since we have the skills compendium, I think that this issue is still valid.
