### ISSUE TITLE
Sort skills

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#87]
Either have an option to click to sort skills, or always keep skills sorted within a category. Regardless of the order you drag and drop them in.

**Comment by scooper4711** [comment]
and if you decide to make the automatic skills all-caps, then sort those at the top of the list.

**Comment by toastygm** [comment]
You can currently drag skills to any order you like; try dragging them around.

**Comment by scooper4711** [comment]
Yes, I'm aware of that. I just like having things sort themselves if we can swing it. It's all about making skills easy to find.
But issue #90 would essentially eliminate the need for this.

**Comment by jpmcdonald** [comment]
Sorting is kind of a personal preference.  How do you treat specialties for example.  Being able to drag them I think is the best option;  An auto sort would require a button or menu item addition.

**Comment by scooper4711** [comment]
The filter option in #90 eliminates the need for this. Closing.
