### ISSUE TITLE
Limited visibility for an actor should present in FFF format

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#89]
I just configured limited visibility for the other players on some actors, and the resulting look is perfect for a FFF format.
The issue is that it shows the profile Description instead of the Biography page.
Make the Biography page description what appears in limited view, and make the Biography default prompt follow the FFF format.

**Comment by toastygm** [comment]
The Biography information is meant to be “secret “; when a stranger looks at you, they don’t know your background or personal details.  Your “description “ is your public information: what people can see or know about you in a few minutes.

Many things in the FFF background are “private “, so I put it in the biography section. I still think that’s the best way.

I will move the bio picture to the limited profile page.

**Comment by scooper4711** [comment]
I was just about to close this ticket.
There's the ability to format text as "secret" and so the profile description can have what's currently there as well as a FFF section. 
The Bio photo is already carried over to the limited vis page.
This is brilliant.

**Comment by scooper4711** [comment]
if anything, make the FFF template the default.
