### ISSUE TITLE
Update the writing prompts in profile and biography

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#92]
The description in on the profile page is what is displayed for other characters when they only have limited visibility. 
Update that to be the FFF format. I personally like the FFF format as a table.
the Biography is more personal for the character, and things like sibling rank etc fit well there.

Update the biography default text to be (perhaps also use a table)
Birthdate:
Birthplace:
Sibling Rank: x of y
Parent(s):
Parent Occupation:
Estrangement:
Clanhead:
Medical Traits:
Psyche Traits:
~~Comliness:~~ (make the FFF field "Appearance" into "Appearance/Comliness or just Comliness)
Motivation:

And then a prompt below the table for "life story"

**Comment by jpmcdonald** [comment]
Comeliness is misspelled throughout. Minor, but a pet peeve of mine.

**Comment by scooper4711** [comment]
Looks awesome! thanks!
