### ISSUE TITLE
Comprehensive price list - kerbul is wrong

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#94]
Kerbul armor gives 5 protection against edged weapons. It is listed as 4 in the comprehensive price compendium
Likewise, it gives 4 on piercing, not 3

**Comment by mrg67** [comment]
I'm looking at the Compendium under Item > Std Armor, and not seeing any Kurbul armor; only cloth, leather, and quilted.  Is there somewhere else that Kurbul is listed?  Or is this issue referring to something else?

**Comment by toastygm** [comment]
Yes, this is in the wrong place.  scooper4711 is referring to another module I have released in alpha that contains the comprehensive price list.  That is a separate project, and not part of this one.

I am going to close this issue since it is not relevant to this project.
