### ISSUE TITLE
Import/Export of character data

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#97]
I'd like to be able to run HarnChar and transform the text output to something which can be imported here as a new character.
To that end, make a JSON (or format of your choice) exporter (so I can see examples of how it should look) and importer (so I can import generated characters)

**Comment by jpmcdonald** [comment]
This is already a standard feature of FoundryVTT.  Right click on any "actor" in the actors directory tab and select Export Data.  It will output to a JSON format; While I've not tried, it, I assume you can import form the same format. Using Import data.

**Comment by scooper4711** [comment]
Thanks. I thought I saw it @ some point, then couldn't find it again.
